### ISSUE TITLE
Error fatal: Invalid object name '%H'

### ISSUE THREAD

**Issue by globad** [pfrankov/git-copy-history#2]
I have the following error on my OS (Windows 7).

`fatal: Invalid object name '%H'`

![screenshot](https://user-images.githubusercontent.com/41075647/62538104-abc6a300-b85a-11e9-97c9-906b50aa2d32.png)

**Comment by globad** [comment]
I made the PR with a little [fix](https://github.com/pfrankov/git-copy-history/pull/3).

**Comment by pfrankov** [comment]
Thanks! Closed.
