### ISSUE TITLE
Doesn't work on Windows system

### ISSUE THREAD

**Issue by globad** [pfrankov/git-copy-history#4]
I've tried to fix it myself, but after two hours of trying, I gave it up.
The problem is that for some reason, the file write and git commit commands are not performed properly.

**Comment by fayriot** [comment]
Tried it on Lubuntu 19.04, get endless "Writing history". It seems a similar problem, have no idea yet

**Comment by pfrankov** [comment]
Yes, it probably will not work on Windows but it definitely should work on Unix-based OS.
I don't have a Windows machine right now so PR is welcomed: probably you should rewrite just syntax of the commands.

**Comment by fayriot** [comment]
On Windows we have 2 problems: 
1) Formatted executable code with indents not working, even commit.md not created
2) GIT_COMMITTER_DATE and GIT_AUTHOR_DATE causes 
`Error: Command failed:
"GIT_COMMITTER_DATE" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)`

I removed that and its working, commit history is correct. I made PR, please check how it works on Linux, i think GIT_COMMITTER_DATE & GIT_AUTHOR_DATE is unnecessary

**Comment by pfrankov** [comment]
Awesome! Thanks! Please see the comments in the PR.

**Comment by globad** [comment]
Thank you! Now it works for me.
