### ISSUE TITLE
Error: Command failed: cd ../local-repo && git config user.name

### ISSUE THREAD

**Issue by daihaminkey** [pfrankov/git-copy-history#6]
Installed clean Ubuntu 19.04 on VM only to test `git-copy-history`.
Doesn't work:

![изображение](https://user-images.githubusercontent.com/39711756/62658843-6f866600-b972-11e9-9d68-e882c1719a82.png)

Error seems familiar with #2

**Comment by daihaminkey** [comment]
Oh, I got it: there is no exception, if you use argument `--author="name"`
But in this case `Writing history` start to work infinitely.

It creates file, but no git history provided.

![изображение](https://user-images.githubusercontent.com/39711756/62659430-04d62a00-b974-11e9-821c-33205a79eaea.png)

**Comment by pfrankov** [comment]
Could you describe how you fixed that?
`--author="name"` is necessary only if you have no configured git name/email in the repo.

**Comment by fayriot** [comment]
> Oh, I got it: there is no exception, if you use argument `--author="name"`
> But in this case `Writing history` start to work infinitely.
> 
> It creates file, but no git history provided.

Seems like child process falls with exception, maybe author incorrect. Can't reproduce

**Comment by daihaminkey** [comment]
Still have this error on this virtual machine.
Clean Ubuntu 19.04, only node.js installed

Without `--author %any_string%` output is  `No commits in current directory. Continue` and then error.
With `--author %any_string%` got infinite writing.

Maybe trouble with 19.04?

**Comment by pfrankov** [comment]
> Without `--author %any_string%` output is `No commits in current directory. Continue` and then error.

This is expected since you've not configured your git settings.

> With `--author %any_string%` got infinite writing.

Have you updated the tool to 1.1.3?
