### ISSUE TITLE
Author conversion support

### ISSUE THREAD

**Issue by daihaminkey** [pfrankov/git-copy-history#7]
### Problem:

Script saves commit author. It is good to stop cheaters, but is you have multiple names/emails - github won't count such commits.

### Case:
aaa@email.com as github email
bbb@email.com as azure email
ccc@email.com as another azure (admin)

After copying azure history, github will think, that all commits made by two another contributors, and not me.

### Screenshots:

**After copying from Azure:**
![изображение](https://user-images.githubusercontent.com/39711756/62686651-ce2cfd80-b9cd-11e9-953e-eff2aa041610.png)

**How it should be:**
![изображение](https://user-images.githubusercontent.com/39711756/62686408-5959c380-b9cd-11e9-9807-de01ea5f7031.png)

### Suggested solution: 
Add multi-author support and option to convert all authors to single one, used on github.

Something like this:
` git-copy-history from ../path --author "bbb@email.com" "ccc@email.com" --target_author "aaa@email.com"`

**Comment by daihaminkey** [comment]
I don't know JS so well to fix this, but this task is interesting to me. 
Won't you mind, if I rewrite it on Python? I'll put link to your link to your repository on readme, of course

**Comment by pfrankov** [comment]
The tool itself does nothing about storing the author's email. This is your global config.
Probably the best solution here is to define git user in the new repo.
```
git config user.name "FIRST_NAME LAST_NAME"
git config user.email "GITHUB_EMAIL@example.com"
```
